export function page(nonce){return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PLO Syntax Lab · Cloud</title>
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='6' fill='%2311233e'/%3E%3Cpath d='M16 5L25 16L16 27L7 16Z' fill='%2345b9ff'/%3E%3C/svg%3E">
<style>html{color-scheme:dark;font:16px/1.6 system-ui,sans-serif;background:#0a1424;color:#edf4ff}*{box-sizing:border-box}body{margin:0}header{border-bottom:1px solid #28405e;padding:22px max(22px,calc((100vw - 1000px)/2));background:#10213b}header strong{font-size:1.35rem}header span{font-size:.9rem;color:#91b9df;margin-left:14px}main{max-width:1000px;margin:38px auto;padding:0 22px}h1{font-size:1.6rem;margin:0 0 12px}h2{font-size:1.15rem;margin-top:32px}p{color:#bad0e8}form{display:grid;grid-template-columns:1fr 2fr auto;gap:20px;align-items:end;background:#13253e;border:1px solid #2c4665;border-radius:12px;padding:24px}label{display:block}input{width:100%;margin-top:7px;font:inherit;color:inherit;background:#0b172a;border:1px solid #4c6889;border-radius:6px;padding:10px}input[type=file]{font-size:.95rem}button{font:inherit;cursor:pointer;border:0;border-radius:6px;padding:12px 18px;background:#45b9ff;color:#07213a;font-weight:650}button:disabled{opacity:.5;cursor:wait}button.secondary{background:#263e5e;color:#eef5ff}a{color:#65c9ff}code{font:14px ui-monospace,monospace;overflow-wrap:anywhere}table{width:100%;border-collapse:collapse;margin-top:18px}th,td{text-align:left;padding:12px;border-bottom:1px solid #294260}th{color:#abc6e4;font-weight:500}small{font-size:.9rem;color:#aac4de}.scroll{overflow:auto}#message{min-height:32px;margin:16px 0;color:#9bd4ff}#message.error{color:#ffb8ad}.empty{padding:24px 0;color:#9ebbd9}aside{margin-top:28px;border-left:3px solid #45b9ff;padding-left:18px}a:focus-visible,button:focus-visible,input:focus-visible{outline:3px solid #a2dbff;outline-offset:3px}@media(max-width:750px){form{grid-template-columns:1fr}main{margin:24px auto}header span{display:block;margin:4px 0 0}th,td{padding:9px}h1{font-size:1.35rem}}</style></head>
<body><header><strong>PLO Syntax Lab</strong><span>Cloud MCP</span></header><main><h1>比較用CSVを登録</h1><p>同じボードのCSVを登録すると、接続したAIから条件の生成・比較・結果出力ができます。</p>
<form id="upload"><label>ボード<input id="board" name="board" value="Ts9h3d" required autocomplete="off" aria-describedby="board-help"></label><label>CSVファイル<input id="csv" name="csv" type="file" accept=".csv,text/csv" multiple required></label><button id="submit" type="submit">登録する</button></form>
<small id="board-help">3〜5枚。UTF-8のhand/combo・weight列。1ファイル2MiB・50,000行まで。</small><div id="message" role="status" aria-live="polite"></div>
<h2>登録済みCSV</h2><button id="reload" class="secondary" type="button">一覧を更新</button><div class="scroll"><table><thead><tr><th>ファイル</th><th>ボード</th><th>行数 / weight</th><th>比較用ID</th></tr></thead><tbody id="datasets"></tbody></table></div><p id="empty" class="empty">読み込み中…</p><p><button id="previous" class="secondary" type="button" disabled>前へ</button> <button id="next" class="secondary" type="button" disabled>次へ</button></p>
<aside><p>AIへの依頼例：<br>「Ts9h3dのナッツガットとナッツオープンエンドを生成し、登録済みCSVを比較して」</p><p>接続先：<code id="endpoint"></code><br><small>Pluginsの作成済みプラグインから接続します。CSV・条件・結果の有効期限は1時間です。</small></p></aside>
<p><a href="/signout-with-chatgpt?return_to=%2F" target="_top">サインアウト</a></p>
<script nonce="${nonce}">
const byId=id=>document.getElementById(id),message=(text,error=false)=>{byId('message').textContent=text;byId('message').className=error?'error':''};byId('endpoint').textContent=location.origin+'/mcp';
async function api(path,options={}){const r=await fetch(path,options),data=await r.json();if(!r.ok||data.ok===false)throw Error(data.error?.message||'処理を完了できませんでした。');return data;}
let offset=0,nextOffset=null;async function reload(){const data=await api('/api/datasets?offset='+offset),rows=data.data.datasets,body=byId('datasets');body.replaceChildren();nextOffset=data.data.nextOffset;byId('previous').disabled=offset===0;byId('next').disabled=nextOffset===null;byId('empty').textContent=rows.length?'':'CSVはまだ登録されていません。';for(const row of rows){const tr=document.createElement('tr');for(const value of [row.name,row.boardKey,row.rowCount+' / '+row.totalWeight,row.datasetId]){const td=document.createElement('td');td.textContent=value;tr.append(td);}body.append(tr);}return data.data;}
async function registerUploaded(input){const r=await api('/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});await reload();return r.data;}
byId('previous').onclick=()=>{offset=Math.max(0,offset-10);reload().catch(e=>message(e.message,true));};byId('next').onclick=()=>{if(nextOffset!==null)offset=nextOffset;reload().catch(e=>message(e.message,true));};byId('reload').onclick=()=>reload().catch(e=>message(e.message,true));byId('upload').onsubmit=async e=>{e.preventDefault();const files=[...byId('csv').files];if(files.length>3){message('一度に登録するCSVは3個までです。',true);return;}byId('submit').disabled=true;let completed=0;try{for(const file of files){if(file.size>2*1024*1024)throw Error(file.name+'は2MiBを超えています。');message(file.name+'を登録中…');const upload=await api('/uploads',{method:'POST',headers:{'Content-Type':'text/csv','X-Plo-File-Name':encodeURIComponent(file.name)},body:file});await registerUploaded({board:byId('board').value,name:file.name,label:file.name,source:{kind:'upload',uploadId:upload.uploadId}});completed++;}message(completed+'個のCSVを登録しました。AIから登録済みCSVを一覧・比較できます。');}catch(error){message((completed?completed+'個の登録は完了。':'')+error.message,true);}finally{byId('submit').disabled=false;}};
reload().catch(e=>message(e.message,true));
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();addEventListener('pagehide',()=>lifecycle.abort(),{once:true});for(const tool of [{name:'plo_cloud_list_datasets',title:'登録済みCSVを一覧',description:'この利用者が登録したCSVのID・ボード・件数を取得し、表示を更新する。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async input=>{if(!input||Object.keys(input).length)throw Error('引数は空のobjectを指定してください。');return reload();}},{name:'plo_cloud_register_upload',title:'アップロード済みCSVを登録',description:'この利用者の未使用uploadIdを指定ボードに登録し、CSV一覧を更新する。PCのパスは受け取らない。',inputSchema:{type:'object',properties:{board:{type:'string'},name:{type:'string'},label:{type:'string'},source:{type:'object',properties:{kind:{const:'upload'},uploadId:{type:'string'}},required:['kind','uploadId'],additionalProperties:false}},required:['board','name','label','source'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:registerUploaded}])try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}
</script></main></body></html>`;}
