'use strict';
const $=id=>document.getElementById(id), base=new URL('.',location.href);
let board='', mode='defaults', defaults=[], custom=[], selected={defaults:new Set(),custom:new Set()}, busy=false, controller=null, savedCsv='', history=[], selectionId='', generation=0;
const el=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
function error(e){$('error').textContent=e?.message||String(e||'');}
async function api(route,data,method='POST',signal){const res=await fetch(new URL(route,base),{method,headers:data===undefined?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data),signal});const result=await res.json();if(!res.ok)throw Error(result.error);return result;}
function normalized(text){const s=text.replace(/10/g,'T').replace(/[\s,]+/g,'');if(!/^(?:[2-9TJQKA][shdc]){3,5}$/i.test(s))throw Error('ボードを3〜5枚で入力してください。');const cards=s.match(/../g).map(c=>c[0].toUpperCase()+c[1].toLowerCase());if(new Set(cards).size!==cards.length)throw Error('同じカードが重複しています。');return cards.join('');}
function active(){return mode==='defaults'?defaults:custom;}
function clearResults(){$('results').replaceChildren();savedCsv='';$('download').disabled=true;}
function changeBoard(next){if(board!==next){board=next;defaults=[];custom=[];selected={defaults:new Set(),custom:new Set()};clearResults();}renderConditions();}
function renderConditions(){const wrap=$('conditions');wrap.replaceChildren();const search=$('condition-search').value.toLowerCase();active().forEach((r,i)=>{if(!r.label.toLowerCase().includes(search))return;const item=el('div');item.className='condition';const label=el('label'),check=el('input');check.type='checkbox';check.checked=selected[mode].has(i);check.disabled=busy||!r.count||!r.syntax;check.onchange=()=>{check.checked?selected[mode].add(i):selected[mode].delete(i);clearResults();};label.append(check,el('span',r.label+' — '+Number(r.count||0).toLocaleString('ja-JP')+'件'));item.append(label,el('code',r.problem||r.syntax));wrap.append(item);});if(!active().length)wrap.append(el('p',mode==='defaults'?'「デフォルト185条件を生成」を押してください。':'生成画面から追加するか条件JSONを読み込んでください。'));}
function setBusy(value){busy=value;$('generate').disabled=value;$('compare').disabled=value;$('cancel').disabled=!value;$('board').disabled=value;$('selection-file').disabled=value;document.querySelectorAll('#files input, input[name=mode], #all').forEach(e=>e.disabled=value);renderConditions();}
async function generate(e){e?.preventDefault();if(busy)return;try{changeBoard(normalized($('board').value));const snapshot=board,version=++generation;controller=new AbortController();setBusy(true);error('');$('progress').textContent='条件を生成しています…';const reply=await api('defaults',{board:snapshot},'POST',controller.signal);if(version!==generation)return;defaults=reply.ranges;selected.defaults=new Set(defaults.flatMap((r,i)=>['L49','L61'].includes(r.cell)&&r.count?[i]:[]));$('progress').textContent='185条件の生成が完了しました。';renderConditions();}catch(e){error(e.name==='AbortError'?'計算を中止しました。':e);$('progress').textContent='';}finally{setBusy(false);controller=null;}}
function addSelection(data){if(busy)return;const next=normalized(data.board.join(''));if(next!==normalized($('board').value))throw Error('生成条件と入力ボードが違います。先にボードを合わせてください。');changeBoard(next);for(const r of data.ranges){const i=custom.findIndex(v=>v.label===r.label&&v.syntax===r.syntax);if(i>=0)selected.custom.add(i);else{selected.custom.add(custom.length);custom.push(r);}}mode='custom';document.querySelector('input[name=mode][value=custom]').checked=true;clearResults();renderConditions();}
function renderResults(record){const rows=record.rows,wrap=$('results');wrap.replaceChildren();wrap.append(el('p','ボード: '+record.board));const div=el('div');div.className='table-wrap';const table=el('table'),head=el('tr');head.append(el('th','条件'),el('th','合計weight'));for(let i=1;i<=rows[0].csv_count;i++)head.append(el('th',rows[0][`csv${i}_label`]));const thead=el('thead');thead.append(head);table.append(thead);const tbody=el('tbody');for(const r of rows){const tr=el('tr');tr.append(el('td',r.label),el('td',r.total_weight));for(let i=1;i<=r.csv_count;i++){const k=`csv${i}`,p=r[k+'_percent'],td=el('td',`${r[k+'_weight_sum']} / ${p===null?'—':p.toFixed(2)+'%'} (${r[k+'_matched_hands']}件)`);if(p!==null){const bar=el('div');bar.className='bar';bar.style.width=p+'%';td.append(bar);}tr.append(td);}tbody.append(tr);}table.append(tbody);div.append(table);wrap.append(div);}
for(let i=1;i<=3;i++){const row=el('div');row.className='file-row';const label=el('label',`CSV${i}${i===3?'（任意）':''}`),file=el('input');file.type='file';file.accept='.csv';file.id=`file${i}`;label.append(file);const nameLabel=el('label','ラベル'),name=el('input');name.id=`label${i}`;name.value=`CSV${i}`;nameLabel.append(name);row.append(label,nameLabel);$('files').append(row);}
$('compare').onclick=async()=>{if(busy)return;try{const current=normalized($('board').value);if(current!==board&&selected[mode].size)throw Error('ボードが変更されています。条件を再生成してください。');changeBoard(current);const inputs=[1,2,3].map(i=>({file:$(`file${i}`).files[0],label:$(`label${i}`).value})).filter(f=>f.file);if(!$('file1').files[0]||!$('file2').files[0])throw Error('CSV1とCSV2を選択してください。');if(inputs.reduce((n,f)=>n+f.file.size,0)>30*1024*1024)throw Error('CSVの合計サイズは30MiBまでです。');const ranges=active().filter((_,i)=>selected[mode].has(i));controller=new AbortController();setBusy(true);clearResults();error('');$('progress').textContent='CSVを比較しています…';const files=await Promise.all(inputs.map(async({file,label})=>({name:file.name,label,text:new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer())})));const reply=await api('compare',{board,ranges,files,all:$('all').checked},'POST',controller.signal);savedCsv=reply.csv;renderResults(reply.record);$('download').disabled=false;$('progress').textContent='比較結果を履歴に保存しました。';await loadHistory();}catch(e){error(e.name==='AbortError'?'計算を中止しました。':e);$('progress').textContent='';}finally{setBusy(false);controller=null;}};
$('cancel').onclick=()=>controller?.abort();
$('board-form').onsubmit=generate;$('board').oninput=()=>{generation++;clearResults();};
$('open-lab').onclick=()=>{try{const url=new URL('lab/',base);url.searchParams.set('board',normalized($('board').value));window.open(url,'plo-generator');}catch(e){error(e);}};
$('selection-file').onchange=async()=>{try{const file=$('selection-file').files[0];if(!file)return;if(file.size>1024*1024)throw Error('条件JSONは1MiBまでです。');const data=JSON.parse(await file.text());await api('selection',data);const reply=await api('selection',undefined,'GET');addSelection(reply.selection);selectionId=reply.selection.id;error('');}catch(e){error(e);}finally{$('selection-file').value='';}};
setInterval(async()=>{if(busy)return;try{const reply=await api('selection',undefined,'GET');if(reply.selection&&reply.selection.id!==selectionId){addSelection(reply.selection);selectionId=reply.selection.id;error('');}}catch(e){error(e);}},2000);
document.querySelectorAll('input[name=mode]').forEach(e=>e.onchange=()=>{mode=e.value;clearResults();renderConditions();});$('all').onchange=clearResults;$('condition-search').oninput=renderConditions;
$('download').onclick=()=>{const url=URL.createObjectURL(new Blob([savedCsv],{type:'text/csv;charset=utf-8'})),a=el('a');a.href=url;a.download='PLO-comparison.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function renderHistory(){const wrap=$('history');wrap.replaceChildren();const q=$('history-search').value.toLowerCase();for(const h of history){if(!(h.board+' '+h.files.map(f=>f.name+' '+f.label).join(' ')).toLowerCase().includes(q))continue;const row=el('div');row.className='history-row';row.append(el('span',`${new Date(h.savedUtc).toLocaleString()} · ${h.board} · ${h.files.map(f=>f.label).join(' / ')}`));const view=el('button','表示'),remove=el('button','削除');view.onclick=async()=>{try{const r=await api('history/'+h.id,undefined,'GET');savedCsv=r.csv;renderResults(r.record);$('download').disabled=false;}catch(e){error(e);}};remove.onclick=async()=>{if(!confirm('この履歴を削除しますか？ 元CSVは削除されません。'))return;try{await api('history/'+h.id,{},'DELETE');await loadHistory();}catch(e){error(e);}};row.append(view,remove);wrap.append(row);}if(!history.length)wrap.append(el('p','履歴はまだありません。'));}
async function loadHistory(){history=(await api('history',undefined,'GET')).history;renderHistory();}
$('refresh-history').onclick=()=>loadHistory().catch(error);$('history-search').oninput=renderHistory;
renderConditions();loadHistory().catch(error);
